import Vue from 'vue'
import { Button, Select, Container, Header, Main, Footer, Menu, MenuItem, Dialog, Table, TableColumn, Row, Col, Tag, Input } from 'element-ui'
Vue.use(Button)
Vue.use(Select)
Vue.use(Container)
Vue.use(Header)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Dialog)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Row)
Vue.use(Col)
Vue.use(Tag)
Vue.use(Button)
Vue.use(Input)